### PR TITLE
Remove useless assignments

### PR DESCRIPTION
**Pull request by Sinepel**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Remove useless assignment, links are already included in `$url` smarty vars
| Type?         | refacto
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes 
| How to test?  | Test to login & logout

### CODE REVIEW

**Comment by NeOMakinG** [comment]
Hey @Sinepel 

https://github.com/PrestaShop/PrestaShop/pull/20403#pullrequestreview-459344749

Care about this comment, I think if you follow it on the #20403, you'll have to follow it there too 😃

**Comment by Sinepel** [comment]
@NeOMakinG You're talking about "We can keep the logout_rul assignment, mark it as deprecated, and change values in templates, wdyt? :)" ?

Thanks :)

**Comment by NeOMakinG** [comment]
@Sinepel yes, and @matks responded to you :)

**Review by NeOMakinG — APPROVED** [review]
LGTM

**Review by Progi1984 — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by matthieu-rolland** [comment]
Thank you @Sinepel !

**Pull request merged**
