### PR TITLE
Deprecate variable for logged in customer

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | This variable is no longer needed. Can I remove it @PierreRambaud?
| Type?         | refacto
| BC breaks?    | no
| Deprecations? | yes
| Fixed ticket? | -
| How to test?  | -

### CODE REVIEW

**Review by PierreRambaud — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

**Comment by PierreRambaud** [comment]
Hey, could you please fix CS fixer, and add a way to test it?

**Comment by Hlavtox** [comment]
@PierreRambaud CS fixed. I think there is nothing to test. This module needs minimal version 1.7.1 and the new variable was already present in this version. ;-)

**Review by PierreRambaud — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Comment by Progi1984** [comment]
@Hlavtox How can the QA test it ?

**Comment by Hlavtox** [comment]
@Progi1984 Install Prestashop 1.7.1.0, update module to this PR, see if template works properly using the new general purpose variable.

**Comment by Progi1984** [comment]
Thanks @Hlavtox & @boubkerbribri

**Pull request merged**
