### PR TITLE
Hook module on reset

### LINKED ISSUE #20552: When reseting ps_customersignin the module isn't hooked anymore in FO
#### Describe the bug

When reseting ps_customersignin the module isn't hooked anymore in FO

#### Steps to Reproduce

1. Go to 'the BO -> module manager
2. Search ps_customersignin
3. Click on reset
4. Go to FO 
5. See that the module isn't hooked anymore 

**Screenshots**

https://drive.google.com/file/d/1YLSILr3OnNyAj4mGjCC2aoxqdokuwDBz/view

#### Additional information

* PrestaShop version: 1.7.6, 1.7.7
* Module version : 2.0.2
* PHP version: 7.1

### PR DESCRIPTION
**Pull request by ghost**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Hook the module on reset
| Type?         | bug fix
| BC breaks?    |  no
| Deprecations? | no
| Fixed ticket? | Fixes https://github.com/PrestaShop/PrestaShop/issues/20552
| How to test?  |  Reser Module and check if is hooked
| Sponsor company| @Touxten

### CODE REVIEW

**Review by Progi1984 — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @okom3pom,

After `resetting` the module or `re-installing` the module `ps_customersignin`.
The module is well hooked to `displayNav2` hook but not in the right position

**Before**
image
image

**After**
image
image

Thank you!

**Comment by PierreRambaud** [comment]
> Hi @okom3pom,
> 
> After `resetting` the module or `re-installing` the module `ps_customersignin`.
> The module is well hooked to `displayNav2` hook but not in the right position
> 
> **Before**
> image
> image
> 
> **After**
> image
> image
> 
> Thank you!

The position is not a problem and only depends on the theme you're using.
The position value is: the latest position added for this hook + one

This is a normal behaviour

**Comment by khouloudbelguith** [comment]
Hi @okom3pom,

It is ok :heavy_check_mark: 
I checked with PS1769, 177x branch, and develop branch.

Thanks, @okom3pom, @PierreRambaud!

**Comment by PierreRambaud** [comment]
Thank you @okom3pom

**Pull request merged**
